version: '3.7'

services:
  api:
    image: school_project_api
    build: 
      context: ./
      dockerfile: ./Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/app
    ports:
      - 8000:80