name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2                  # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: public.ecr.aws/h6w9d2s6           # set this to your Amazon ECR repository name
  CONTAINER_NAME: school-project           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/h6w9d2s6
          docker build -t school_project_api:latest public.ecr.aws/h6w9d2s6/school-project:latest
          docker push public.ecr.aws/h6w9d2s6/school-project:latest
